paths:
  refs_dir: datasets/refs
  gens_dir: datasets/gens
  categories: metadata/categories.csv
  hdri: assets/lights.hdr
  out_dir: outputs
  blender_exe: "C:\\Program Files\\Blender Foundation\\Blender 4.5\\blender.exe"

render:
  engine: cycles
  samples: 256
  fov_deg: 42
  camera:
    radius: 2.2
    azimuth_deg: 45
    elevation_deg: 35
  object_prez_rot_z_deg: 20
  filmic: true
  film_transparent: true
  denoiser: OIDN
  resolution: 1024

preprocess:
  canvas_px: 1024
  bg_rgb: [0, 0, 0]
  crop_margin_frac: 0.05
  feather_px: 2
  label_bar_frac: 0.06
  segmentation_model: "u2net"  # or "u2net_human_seg" for people

scoring:
  models: [gemini-2.5-pro]  # Gemini 2.5 Pro for complex visual reasoning
  repeats: 3
  rubric_weights:
    color_palette: 40
    material_finish: 25
    texture_identity: 15
    texture_scale_placement: 20
  temperature: 0.0
  top_p: 1.0
  use_batch_mode: true  # Create timestamped batches to accumulate results over time
  results_dir: null  # null = use default (outputs/llm_calls), or set path for shared directory

sentinels:
  enabled: false  # Phase 2 feature
  positive_threshold: 85
  negative_threshold: 25

translation:
  enabled: true  # Enable Italian translation of LLM rationales
  model: gemini-2.5-flash  # Fast and cost-effective model for translation
  cache_translations: true  # Cache translations to avoid re-translating

data_source:
  type: legacy  # "legacy" (data/database.csv) or "archi3d" (tables/generations.csv)

  # Legacy source options (for validation study)
  base_path: null  # Set in config.local.yaml (e.g., "C:/Users/.../Testing")
  dataset_folder: dataset  # Relative to base_path (folder with reference images)
  database_csv: data/database.csv  # Relative to VFScore root
  selected_objects_csv: data/selected_objects_optimized.csv  # Relative to VFScore root

  # Archi3D source options (for future integration)
  # workspace: null  # Path to archi3D workspace (e.g., path to Testing/)
  # run_id: null  # Optional: filter by specific run_id (e.g., "2025-08-17_v1")
  # items_csv: null  # Optional: override default tables/items.csv
  # generations_csv: null  # Optional: override default tables/generations.csv

logging:
  level: INFO
  save_prompts: true
  save_timing: true
  save_hashes: true

phase_1_features:
  enabled: true
  skip_sentinels: true
  single_model_only: true
  basic_reporting: true